# Generated by Django 3.1.7 on 2021-03-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_project_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_level',
            field=models.IntegerField(default=0),
        ),
    ]
