# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210315_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_allowed_viewers',
            field=models.CharField(blank=True, default='', max_length=6000),
        ),
    ]
