# Generated by Codex on 2026-06-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projects_viewer_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.CharField(max_length=30)),
                ('req_description', models.TextField()),
                ('chapter_id', models.CharField(blank=True, default='', max_length=20)),
                ('chapter_name', models.CharField(blank=True, default='', max_length=255)),
                ('section_id', models.CharField(blank=True, default='', max_length=30)),
                ('section_name', models.CharField(blank=True, default='', max_length=255)),
                ('level1', models.CharField(blank=True, default='', max_length=10)),
                ('level2', models.CharField(blank=True, default='', max_length=10)),
                ('level3', models.CharField(blank=True, default='', max_length=10)),
                ('cwe', models.CharField(blank=True, default='', max_length=255)),
                ('nist', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('na', 'N/A'), ('complete', 'Complete'), ('incomplete', 'Incomplete'), ('review', 'Needs Review')], default='na', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=150)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='projects.projects')),
            ],
            options={
                'ordering': ['chapter_id', 'section_id', 'req_id'],
                'unique_together': {('project', 'req_id')},
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.projects')),
            ],
            options={
                'unique_together': {('project', 'username')},
            },
        ),
        migrations.CreateModel(
            name='RequirementEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='projects.projectrequirement')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.projectrequirement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=80)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='projects.projects')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectrequirement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
