# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_workspace_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='asvs_version',
            field=models.CharField(default='5.0', max_length=20),
        ),
    ]
